#!/usr/bin/env python3
"""Compatibility plotting entry point for C5b.

The main plotting is generated by analyze_c5b_refinement.py so this script
only verifies that the expected CSV/figure outputs exist.
"""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    required = [
        ROOT / "c5b_case_summary.csv",
        ROOT / "c5b_center_pressure_comparison.csv",
        ROOT / "c5b_averaging_radius_sensitivity.csv",
        ROOT / "figures" / "c5b_center_normalized_pressure_primary_radius.png",
    ]
    missing = [path for path in required if not path.exists()]
    if missing:
        raise SystemExit("Missing C5b outputs: " + ", ".join(str(path) for path in missing))
    print("C5b plot outputs verified.")


if __name__ == "__main__":
    main()
